rtc: fix sign-conversion warnings when writing setup registers
Building tests shows a few of these errors in rtc.c. The issue is that
despite both being 32 bits on this platform, 'long unsigned int' still
has a higher conversion rank than 'unsigned int'. The datetime_t fields
are int8_t or int16_t which does get sign-extended when converting up to
uint, and then it's converted again up to uint32_t (unsigned long) when
writing to the register.

There's already logic checks in place to ensure that values are positive
and in range, so just casting directly to uint32_t rather than uint
squashes these warnings. Without those checks, it would be necessary to
mask each field with the corresponding _BITS value after shifting.

/workspace/pico-sdk/src/rp2_common/hardware_rtc/rtc.c: In function 'rtc_set_datetime':
/workspace/pico-sdk/src/rp2_common/hardware_rtc/rtc.c:68:23: error: conversion to 'io_rw_32' {aka 'long unsigned int'} from 'unsigned int' may change the sign of the result [-Werror=sign-conversion]
   68 |     rtc_hw->setup_0 = (((uint)t->year)  << RTC_SETUP_0_YEAR_LSB ) |
      |                       ^